.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH eksup 1  "eksup 0.14.0" 
.SH NAME
eksup \- A CLI to aid in upgrading Amazon EKS clusters
.SH SYNOPSIS
\fBeksup\fR [\fB\-v\fR|\fB\-\-verbose\fR]... [\fB\-q\fR|\fB\-\-quiet\fR]... [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
A CLI to aid in upgrading Amazon EKS clusters
.SH OPTIONS
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase logging verbosity
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Decrease logging verbosity
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
eksup\-analyze(1)
Analyze an Amazon EKS cluster for potential upgrade issues
.TP
eksup\-create(1)
Create artifacts using the analysis data
.TP
eksup\-completion(1)
Generate shell completion script for the given shell
.TP
eksup\-man(1)
Generate the man page for eksup
.TP
eksup\-help(1)
Print this message or the help of the given subcommand(s)
.SH VERSION
v0.14.0
.SH AUTHORS
Bryant Biggs <bryantbiggs@gmail.com>
