tab_spaces=2
max_width = 120
comment_width = 120
wrap_comments = true
edition = "2021"
reorder_imports = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_modules = true
merge_derives = true
use_field_init_shorthand = true
format_macro_matchers = true
format_macro_bodies = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
